spring:
  application:
    name: spring-jdbc-homework
  datasource:
    url: jdbc:h2:file:~/librarydb;AUTO_SERVER=true;IFEXISTS=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false
  h2:
    console:
      enabled: true
  shell:
    interactive:
      enabled: false
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: book-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: "bookCreateRequest:ru.diasoft.spring.kafka.dto.BookCreateRequestEvent,bookCreatedEvent:ru.diasoft.spring.kafka.dto.BookCreatedEvent"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: "bookCreateRequest:ru.diasoft.spring.kafka.dto.BookCreateRequestEvent,bookCreatedEvent:ru.diasoft.spring.kafka.dto.BookCreatedEvent"

book-service:
  url: http://localhost:8080

kafka:
  topics:
    book-create-requests: book-create-requests
    book-events: book-events

logging:
  level:
    org.springframework.jdbc: DEBUG
