server:
  port: 8081

spring:
  application:
    name: book-client-service

book-service:
  url: http://localhost:8080

resilience4j:
  circuitbreaker:
    instances:
      bookService:
        register-health-indicator: true
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 10s
        failure-rate-threshold: 50
        record-exceptions:
          - java.lang.Exception
  timelimiter:
    instances:
      bookService:
        timeout-duration: 3s

management:
  endpoints:
    web:
      exposure:
        include: health,info,circuitbreakers,circuitbreakerevents
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true

logging:
  level:
    ru.diasoft.spring.client: DEBUG
    io.github.resilience4j: DEBUG
